<?php

declare(strict_types=1);

namespace Adrigar94\ValueObjectCraft\Domain\Currency;

use Adrigar94\ValueObjectCraft\Primitive\Enum\EnumValueObject;

class CurrencyValueObject extends EnumValueObject
{
    public const ADB_Unit_of_Account = "XUA";
    public const Afghani = "AFN";
    public const Algerian_Dinar = "DZD";
    public const Argentine_Peso = "ARS";
    public const Armenian_Dram = "AMD";
    public const Aruban_Florin = "AWG";
    public const Australian_Dollar = "AUD";
    public const Azerbaijanian_Manat = "AZN";
    public const Bahamian_Dollar = "BSD";
    public const Bahraini_Dinar = "BHD";
    public const Baht = "THB";
    public const Balboa = "PAB";
    public const Barbados_Dollar = "BBD";
    public const Belarussian_Ruble = "BYN";
    public const Belize_Dollar = "BZD";
    public const Bermudian_Dollar = "BMD";
    public const Bolivar = "VEF";
    public const Boliviano = "BOB";
    public const Brazilian_Real = "BRL";
    public const Brunei_Dollar = "BND";
    public const Bulgarian_Lev = "BGN";
    public const Burundi_Franc = "BIF";
    public const CFA_Franc_BCEAO = "XOF";
    public const CFA_Franc_BEAC = "XAF";
    public const CFP_Franc = "XPF";
    public const Cabo_Verde_Escudo = "CVE";
    public const Canadian_Dollar = "CAD";
    public const Cayman_Islands_Dollar = "KYD";
    public const Chilean_Peso = "CLP";
    public const Colombian_Peso = "COP";
    public const Comoro_Franc = "KMF";
    public const Congolese_Franc = "CDF";
    public const Convertible_Mark = "BAM";
    public const Cordoba_Oro = "NIO";
    public const Costa_Rican_Colon = "CRC";
    public const Cuban_Peso = "CUP";
    public const Czech_Koruna = "CZK";
    public const Dalasi = "GMD";
    public const Danish_Krone = "DKK";
    public const Denar = "MKD";
    public const Djibouti_Franc = "DJF";
    public const Dobra = "STN";
    public const Dominican_Peso = "DOP";
    public const Dong = "VND";
    public const East_Caribbean_Dollar = "XCD";
    public const Egyptian_Pound = "EGP";
    public const El_Salvador_Colon = "SVC";
    public const Ethiopian_Birr = "ETB";
    public const Euro = "EUR";
    public const Falkland_Islands_Pound = "FKP";
    public const Fiji_Dollar = "FJD";
    public const Forint = "HUF";
    public const Ghana_Cedi = "GHS";
    public const Gibraltar_Pound = "GIP";
    public const Gourde = "HTG";
    public const Guarani = "PYG";
    public const Guinea_Franc = "GNF";
    public const Guyana_Dollar = "GYD";
    public const Hong_Kong_Dollar = "HKD";
    public const Hryvnia = "UAH";
    public const Iceland_Krona = "ISK";
    public const Indian_Rupee = "INR";
    public const Iranian_Rial = "IRR";
    public const Iraqi_Dinar = "IQD";
    public const Jamaican_Dollar = "JMD";
    public const Jordanian_Dinar = "JOD";
    public const Kenyan_Shilling = "KES";
    public const Kina = "PGK";
    public const Kip = "LAK";
    public const Kuna = "HRK";
    public const Kuwaiti_Dinar = "KWD";
    public const Kwacha = "MWK";
    public const Kwanza = "AOA";
    public const Kyat = "MMK";
    public const Lari = "GEL";
    public const Lebanese_Pound = "LBP";
    public const Lek = "ALL";
    public const Lempira = "HNL";
    public const Leone = "SLE";
    public const Liberian_Dollar = "LRD";
    public const Libyan_Dinar = "LYD";
    public const Lilangeni = "SZL";
    public const Loti = "LSL";
    public const Malagasy_Ariary = "MGA";
    public const Malaysian_Ringgit = "MYR";
    public const Mauritius_Rupee = "MUR";
    public const Mexican_Peso = "MXN";
    public const Moldovan_Leu = "MDL";
    public const Moroccan_Dirham = "MAD";
    public const Mozambique_Metical = "MZN";
    public const Mvdol = "BOV";
    public const Naira = "NGN";
    public const Nakfa = "ERN";
    public const Namibia_Dollar = "NAD";
    public const Nepalese_Rupee = "NPR";
    public const Netherlands_Antillean_Guilder = "ANG";
    public const New_Israeli_Sheqel = "ILS";
    public const New_Taiwan_Dollar = "TWD";
    public const New_Zealand_Dollar = "NZD";
    public const Ngultrum = "BTN";
    public const North_Korean_Won = "KPW";
    public const Norwegian_Krone = "NOK";
    public const Nuevo_Sol = "PEN";
    public const Ouguiya = "MRU";
    public const Pakistan_Rupee = "PKR";
    public const Pataca = "MOP";
    public const Pa’anga = "TOP";
    public const Peso_Convertible = "CUC";
    public const Peso_Uruguayo = "UYU";
    public const Philippine_Peso = "PHP";
    public const Pound_Sterling = "GBP";
    public const Pula = "BWP";
    public const Qatari_Rial = "QAR";
    public const Quetzal = "GTQ";
    public const Rand = "ZAR";
    public const Rial_Omani = "OMR";
    public const Riel = "KHR";
    public const Romanian_Leu = "RON";
    public const Rufiyaa = "MVR";
    public const Rupiah = "IDR";
    public const Russian_Ruble = "RUB";
    public const Rwanda_Franc = "RWF";
    public const Saint_Helena_Pound = "SHP";
    public const Saudi_Riyal = "SAR";
    public const Serbian_Dinar = "RSD";
    public const Seychelles_Rupee = "SCR";
    public const Singapore_Dollar = "SGD";
    public const Solomon_Islands_Dollar = "SBD";
    public const Som = "KGS";
    public const Somali_Shilling = "SOS";
    public const Somoni = "TJS";
    public const South_Sudanese_Pound = "SSP";
    public const Sri_Lanka_Rupee = "LKR";
    public const Sucre = "XSU";
    public const Sudanese_Pound = "SDG";
    public const Surinam_Dollar = "SRD";
    public const Swedish_Krona = "SEK";
    public const Swiss_Franc = "CHF";
    public const Syrian_Pound = "SYP";
    public const Taka = "BDT";
    public const Tala = "WST";
    public const Tanzanian_Shilling = "TZS";
    public const Tenge = "KZT";
    public const Trinidad_and_Tobago_Dollar = "TTD";
    public const Tugrik = "MNT";
    public const Tunisian_Dinar = "TND";
    public const Turkish_Lira = "TRY";
    public const Turkmenistan_New_Manat = "TMT";
    public const UAE_Dirham = "AED";
    public const US_Dollar = "USD";
    public const Uganda_Shilling = "UGX";
    public const Unidad_de_Fomento = "CLF";
    public const Unidad_de_Valor_Real = "COU";
    public const Uzbekistan_Sum = "UZS";
    public const Vatu = "VUV";
    public const WIR_Euro = "CHE";
    public const WIR_Franc = "CHW";
    public const Won = "KRW";
    public const Yemeni_Rial = "YER";
    public const Yen = "JPY";
    public const Yuan_Renminbi = "CNY";
    public const Zambian_Kwacha = "ZMW";
    public const Zimbabwe_Dollar = "ZWL";
    public const Zlloty = "PLN";

    protected function valueMapping(): array
    {
        return [
            self::ADB_Unit_of_Account => "ADB Unit of Account",
            self::Afghani => "Afghani",
            self::Algerian_Dinar => "Algerian Dinar",
            self::Argentine_Peso => "Argentine Peso",
            self::Armenian_Dram => "Armenian Dram",
            self::Aruban_Florin => "Aruban Florin",
            self::Australian_Dollar => "Australian Dollar",
            self::Azerbaijanian_Manat => "Azerbaijanian Manat",
            self::Bahamian_Dollar => "Bahamian Dollar",
            self::Bahraini_Dinar => "Bahraini Dinar",
            self::Baht => "Baht",
            self::Balboa => "Balboa",
            self::Barbados_Dollar => "Barbados Dollar",
            self::Belarussian_Ruble => "Belarussian Ruble",
            self::Belize_Dollar => "Belize Dollar",
            self::Bermudian_Dollar => "Bermudian Dollar",
            self::Bolivar => "Bolivar",
            self::Boliviano => "Boliviano",
            self::Brazilian_Real => "Brazilian Real",
            self::Brunei_Dollar => "Brunei Dollar",
            self::Bulgarian_Lev => "Bulgarian Lev",
            self::Burundi_Franc => "Burundi Franc",
            self::CFA_Franc_BCEAO => "CFA Franc BCEAO",
            self::CFA_Franc_BEAC => "CFA Franc BEAC",
            self::CFP_Franc => "CFP Franc",
            self::Cabo_Verde_Escudo => "Cabo Verde Escudo",
            self::Canadian_Dollar => "Canadian Dollar",
            self::Cayman_Islands_Dollar => "Cayman Islands Dollar",
            self::Chilean_Peso => "Chilean Peso",
            self::Colombian_Peso => "Colombian Peso",
            self::Comoro_Franc => "Comoro Franc",
            self::Congolese_Franc => "Congolese Franc",
            self::Convertible_Mark => "Convertible Mark",
            self::Cordoba_Oro => "Cordoba Oro",
            self::Costa_Rican_Colon => "Costa Rican Colon",
            self::Cuban_Peso => "Cuban Peso",
            self::Czech_Koruna => "Czech Koruna",
            self::Dalasi => "Dalasi",
            self::Danish_Krone => "Danish Krone",
            self::Denar => "Denar",
            self::Djibouti_Franc => "Djibouti Franc",
            self::Dobra => "Dobra",
            self::Dominican_Peso => "Dominican Peso",
            self::Dong => "Dong",
            self::East_Caribbean_Dollar => "East Caribbean Dollar",
            self::Egyptian_Pound => "Egyptian Pound",
            self::El_Salvador_Colon => "El Salvador Colon",
            self::Ethiopian_Birr => "Ethiopian Birr",
            self::Euro => "Euro",
            self::Falkland_Islands_Pound => "Falkland Islands Pound",
            self::Fiji_Dollar => "Fiji Dollar",
            self::Forint => "Forint",
            self::Ghana_Cedi => "Ghana Cedi",
            self::Gibraltar_Pound => "Gibraltar Pound",
            self::Gourde => "Gourde",
            self::Guarani => "Guarani",
            self::Guinea_Franc => "Guinea Franc",
            self::Guyana_Dollar => "Guyana Dollar",
            self::Hong_Kong_Dollar => "Hong Kong Dollar",
            self::Hryvnia => "Hryvnia",
            self::Iceland_Krona => "Iceland Krona",
            self::Indian_Rupee => "Indian Rupee",
            self::Iranian_Rial => "Iranian Rial",
            self::Iraqi_Dinar => "Iraqi Dinar",
            self::Jamaican_Dollar => "Jamaican Dollar",
            self::Jordanian_Dinar => "Jordanian Dinar",
            self::Kenyan_Shilling => "Kenyan Shilling",
            self::Kina => "Kina",
            self::Kip => "Kip",
            self::Kuna => "Kuna",
            self::Kuwaiti_Dinar => "Kuwaiti Dinar",
            self::Kwacha => "Kwacha",
            self::Kwanza => "Kwanza",
            self::Kyat => "Kyat",
            self::Lari => "Lari",
            self::Lebanese_Pound => "Lebanese Pound",
            self::Lek => "Lek",
            self::Lempira => "Lempira",
            self::Leone => "Leone",
            self::Liberian_Dollar => "Liberian Dollar",
            self::Libyan_Dinar => "Libyan Dinar",
            self::Lilangeni => "Lilangeni",
            self::Loti => "Loti",
            self::Malagasy_Ariary => "Malagasy Ariary",
            self::Malaysian_Ringgit => "Malaysian Ringgit",
            self::Mauritius_Rupee => "Mauritius Rupee",
            self::Mexican_Peso => "Mexican Peso",
            self::Moldovan_Leu => "Moldovan Leu",
            self::Moroccan_Dirham => "Moroccan Dirham",
            self::Mozambique_Metical => "Mozambique Metical",
            self::Mvdol => "Mvdol",
            self::Naira => "Naira",
            self::Nakfa => "Nakfa",
            self::Namibia_Dollar => "Namibia Dollar",
            self::Nepalese_Rupee => "Nepalese Rupee",
            self::Netherlands_Antillean_Guilder => "Netherlands Antillean Guilder",
            self::New_Israeli_Sheqel => "New Israeli Sheqel",
            self::New_Taiwan_Dollar => "New Taiwan Dollar",
            self::New_Zealand_Dollar => "New Zealand Dollar",
            self::Ngultrum => "Ngultrum",
            self::North_Korean_Won => "North Korean Won",
            self::Norwegian_Krone => "Norwegian Krone",
            self::Nuevo_Sol => "Nuevo Sol",
            self::Ouguiya => "Ouguiya",
            self::Pakistan_Rupee => "Pakistan Rupee",
            self::Pataca => "Pataca",
            self::Pa’anga => "Pa’anga",
            self::Peso_Convertible => "Peso Convertible",
            self::Peso_Uruguayo => "Peso Uruguayo",
            self::Philippine_Peso => "Philippine Peso",
            self::Pound_Sterling => "Pound Sterling",
            self::Pula => "Pula",
            self::Qatari_Rial => "Qatari Rial",
            self::Quetzal => "Quetzal",
            self::Rand => "Rand",
            self::Rial_Omani => "Rial Omani",
            self::Riel => "Riel",
            self::Romanian_Leu => "Romanian Leu",
            self::Rufiyaa => "Rufiyaa",
            self::Rupiah => "Rupiah",
            self::Russian_Ruble => "Russian Ruble",
            self::Rwanda_Franc => "Rwanda Franc",
            self::Saint_Helena_Pound => "Saint Helena Pound",
            self::Saudi_Riyal => "Saudi Riyal",
            self::Serbian_Dinar => "Serbian Dinar",
            self::Seychelles_Rupee => "Seychelles Rupee",
            self::Singapore_Dollar => "Singapore Dollar",
            self::Solomon_Islands_Dollar => "Solomon Islands Dollar",
            self::Som => "Som",
            self::Somali_Shilling => "Somali Shilling",
            self::Somoni => "Somoni",
            self::South_Sudanese_Pound => "South Sudanese Pound",
            self::Sri_Lanka_Rupee => "Sri Lanka Rupee",
            self::Sucre => "Sucre",
            self::Sudanese_Pound => "Sudanese Pound",
            self::Surinam_Dollar => "Surinam Dollar",
            self::Swedish_Krona => "Swedish Krona",
            self::Swiss_Franc => "Swiss Franc",
            self::Syrian_Pound => "Syrian Pound",
            self::Taka => "Taka",
            self::Tala => "Tala",
            self::Tanzanian_Shilling => "Tanzanian Shilling",
            self::Tenge => "Tenge",
            self::Trinidad_and_Tobago_Dollar => "Trinidad and Tobago Dollar",
            self::Tugrik => "Tugrik",
            self::Tunisian_Dinar => "Tunisian Dinar",
            self::Turkish_Lira => "Turkish Lira",
            self::Turkmenistan_New_Manat => "Turkmenistan New Manat",
            self::UAE_Dirham => "UAE Dirham",
            self::US_Dollar => "US Dollar",
            self::Uganda_Shilling => "Uganda Shilling",
            self::Unidad_de_Fomento => "Unidad de Fomento",
            self::Unidad_de_Valor_Real => "Unidad de Valor Real",
            self::Uzbekistan_Sum => "Uzbekistan Sum",
            self::Vatu => "Vatu",
            self::WIR_Euro => "WIR Euro",
            self::WIR_Franc => "WIR Franc",
            self::Won => "Won",
            self::Yemeni_Rial => "Yemeni Rial",
            self::Yen => "Yen",
            self::Yuan_Renminbi => "Yuan Renminbi",
            self::Zambian_Kwacha => "Zambian Kwacha",
            self::Zimbabwe_Dollar => "Zimbabwe Dollar",
            self::Zlloty => "Zloty"
        ];
    }

    public function valueToCurrencyNumber(): ?string
    {
        $codes = [
            "XUA" => "965",
            "AFN" => "971",
            "DZD" => "012",
            "ARS" => "032",
            "AMD" => "051",
            "AWG" => "533",
            "AUD" => "036",
            "AZN" => "944",
            "BSD" => "044",
            "BHD" => "048",
            "THB" => "764",
            "PAB" => "590",
            "BBD" => "052",
            "BYN" => "933",
            "BZD" => "084",
            "BMD" => "060",
            "VEF" => "937",
            "BOB" => "068",
            "BRL" => "986",
            "BND" => "096",
            "BGN" => "975",
            "BIF" => "108",
            "XOF" => "952",
            "XAF" => "950",
            "XPF" => "953",
            "CVE" => "132",
            "CAD" => "124",
            "KYD" => "136",
            "CLP" => "152",
            "COP" => "170",
            "KMF" => "174",
            "CDF" => "976",
            "BAM" => "977",
            "NIO" => "558",
            "CRC" => "188",
            "CUP" => "192",
            "CZK" => "203",
            "GMD" => "270",
            "DKK" => "208",
            "MKD" => "807",
            "DJF" => "262",
            "STN" => "930",
            "DOP" => "214",
            "VND" => "704",
            "XCD" => "951",
            "EGP" => "818",
            "SVC" => "222",
            "ETB" => "230",
            "EUR" => "978",
            "FKP" => "238",
            "FJD" => "242",
            "HUF" => "348",
            "GHS" => "936",
            "GIP" => "292",
            "HTG" => "332",
            "PYG" => "600",
            "GNF" => "324",
            "GYD" => "328",
            "HKD" => "344",
            "UAH" => "980",
            "ISK" => "352",
            "INR" => "356",
            "IRR" => "364",
            "IQD" => "368",
            "JMD" => "388",
            "JOD" => "400",
            "KES" => "404",
            "PGK" => "598",
            "LAK" => "418",
            "HRK" => "191",
            "KWD" => "414",
            "MWK" => "454",
            "AOA" => "973",
            "MMK" => "104",
            "GEL" => "981",
            "LBP" => "422",
            "ALL" => "008",
            "HNL" => "340",
            "SLE" => "925",
            "LRD" => "430",
            "LYD" => "434",
            "SZL" => "748",
            "LSL" => "426",
            "MGA" => "969",
            "MYR" => "458",
            "MUR" => "480",
            "MXN" => "484",
            "MDL" => "498",
            "MAD" => "504",
            "MZN" => "943",
            "BOV" => "984",
            "NGN" => "566",
            "ERN" => "232",
            "NAD" => "516",
            "NPR" => "524",
            "ANG" => "532",
            "ILS" => "376",
            "TWD" => "901",
            "NZD" => "554",
            "BTN" => "064",
            "KPW" => "408",
            "NOK" => "578",
            "PEN" => "604",
            "MRU" => "929",
            "PKR" => "586",
            "MOP" => "446",
            "TOP" => "776",
            "CUC" => "931",
            "UYU" => "858",
            "PHP" => "608",
            "GBP" => "826",
            "BWP" => "072",
            "QAR" => "634",
            "GTQ" => "320",
            "ZAR" => "710",
            "OMR" => "512",
            "KHR" => "116",
            "RON" => "946",
            "MVR" => "462",
            "IDR" => "360",
            "RUB" => "643",
            "RWF" => "646",
            "SHP" => "654",
            "SAR" => "682",
            "RSD" => "941",
            "SCR" => "690",
            "SGD" => "702",
            "SBD" => "090",
            "KGS" => "417",
            "SOS" => "706",
            "TJS" => "972",
            "SSP" => "728",
            "LKR" => "144",
            "XSU" => "994",
            "SDG" => "938",
            "SRD" => "968",
            "SEK" => "752",
            "CHF" => "756",
            "SYP" => "760",
            "BDT" => "050",
            "WST" => "882",
            "TZS" => "834",
            "KZT" => "398",
            "TTD" => "780",
            "MNT" => "496",
            "TND" => "788",
            "TRY" => "949",
            "TMT" => "934",
            "AED" => "784",
            "USD" => "840",
            "UGX" => "800",
            "CLF" => "990",
            "COU" => "970",
            "UZS" => "860",
            "VUV" => "548",
            "CHE" => "947",
            "CHW" => "948",
            "KRW" => "410",
            "YER" => "886",
            "JPY" => "392",
            "CNY" => "156",
            "ZMW" => "967",
            "ZWL" => "932",
            "PLN" => "985",
        ];

        return array_key_exists($this->value(), $codes) ? $codes[$this->value()] : null;
    }
}
