<?php

declare(strict_types=1);

namespace Adrigar94\ValueObjectCraft\Domain\Currency;

use Adrigar94\ValueObjectCraft\Primitive\Enum\EnumValueObject;

class CurrencyValueObject extends EnumValueObject
{
    public const ADB_Unit_of_Account = "ADB Unit of Account";
    public const Afghani = "Afghani";
    public const Algerian_Dinar = "Algerian Dinar";
    public const Argentine_Peso = "Argentine Peso";
    public const Armenian_Dram = "Armenian Dram";
    public const Aruban_Florin = "Aruban Florin";
    public const Australian_Dollar = "Australian Dollar";
    public const Azerbaijanian_Manat = "Azerbaijanian Manat";
    public const Bahamian_Dollar = "Bahamian Dollar";
    public const Bahraini_Dinar = "Bahraini Dinar";
    public const Baht = "Baht";
    public const Balboa = "Balboa";
    public const Barbados_Dollar = "Barbados Dollar";
    public const Belarussian_Ruble = "Belarussian Ruble";
    public const Belize_Dollar = "Belize Dollar";
    public const Bermudian_Dollar = "Bermudian Dollar";
    public const Bolivar = "Bolivar";
    public const Boliviano = "Boliviano";
    public const Brazilian_Real = "Brazilian Real";
    public const Brunei_Dollar = "Brunei Dollar";
    public const Bulgarian_Lev = "Bulgarian Lev";
    public const Burundi_Franc = "Burundi Franc";
    public const CFA_Franc_BCEAO = "CFA Franc BCEAO";
    public const CFA_Franc_BEAC = "CFA Franc BEAC";
    public const CFP_Franc = "CFP Franc";
    public const Cabo_Verde_Escudo = "Cabo Verde Escudo";
    public const Canadian_Dollar = "Canadian Dollar";
    public const Cayman_Islands_Dollar = "Cayman Islands Dollar";
    public const Chilean_Peso = "Chilean Peso";
    public const Colombian_Peso = "Colombian Peso";
    public const Comoro_Franc = "Comoro Franc";
    public const Congolese_Franc = "Congolese Franc";
    public const Convertible_Mark = "Convertible Mark";
    public const Cordoba_Oro = "Cordoba Oro";
    public const Costa_Rican_Colon = "Costa Rican Colon";
    public const Cuban_Peso = "Cuban Peso";
    public const Czech_Koruna = "Czech Koruna";
    public const Dalasi = "Dalasi";
    public const Danish_Krone = "Danish Krone";
    public const Denar = "Denar";
    public const Djibouti_Franc = "Djibouti Franc";
    public const Dobra = "Dobra";
    public const Dominican_Peso = "Dominican Peso";
    public const Dong = "Dong";
    public const East_Caribbean_Dollar = "East Caribbean Dollar";
    public const Egyptian_Pound = "Egyptian Pound";
    public const El_Salvador_Colon = "El Salvador Colon";
    public const Ethiopian_Birr = "Ethiopian Birr";
    public const Euro = "Euro";
    public const Falkland_Islands_Pound = "Falkland Islands Pound";
    public const Fiji_Dollar = "Fiji Dollar";
    public const Forint = "Forint";
    public const Ghana_Cedi = "Ghana Cedi";
    public const Gibraltar_Pound = "Gibraltar Pound";
    public const Gourde = "Gourde";
    public const Guarani = "Guarani";
    public const Guinea_Franc = "Guinea Franc";
    public const Guyana_Dollar = "Guyana Dollar";
    public const Hong_Kong_Dollar = "Hong Kong Dollar";
    public const Hryvnia = "Hryvnia";
    public const Iceland_Krona = "Iceland Krona";
    public const Indian_Rupee = "Indian Rupee";
    public const Iranian_Rial = "Iranian Rial";
    public const Iraqi_Dinar = "Iraqi Dinar";
    public const Jamaican_Dollar = "Jamaican Dollar";
    public const Jordanian_Dinar = "Jordanian Dinar";
    public const Kenyan_Shilling = "Kenyan Shilling";
    public const Kina = "Kina";
    public const Kip = "Kip";
    public const Kuna = "Kuna";
    public const Kuwaiti_Dinar = "Kuwaiti Dinar";
    public const Kwacha = "Kwacha";
    public const Kwanza = "Kwanza";
    public const Kyat = "Kyat";
    public const Lari = "Lari";
    public const Lebanese_Pound = "Lebanese Pound";
    public const Lek = "Lek";
    public const Lempira = "Lempira";
    public const Leone = "Leone";
    public const Liberian_Dollar = "Liberian Dollar";
    public const Libyan_Dinar = "Libyan Dinar";
    public const Lilangeni = "Lilangeni";
    public const Loti = "Loti";
    public const Malagasy_Ariary = "Malagasy Ariary";
    public const Malaysian_Ringgit = "Malaysian Ringgit";
    public const Mauritius_Rupee = "Mauritius Rupee";
    public const Mexican_Peso = "Mexican Peso";
    public const Moldovan_Leu = "Moldovan Leu";
    public const Moroccan_Dirham = "Moroccan Dirham";
    public const Mozambique_Metical = "Mozambique Metical";
    public const Mvdol = "Mvdol";
    public const Naira = "Naira";
    public const Nakfa = "Nakfa";
    public const Namibia_Dollar = "Namibia Dollar";
    public const Nepalese_Rupee = "Nepalese Rupee";
    public const Netherlands_Antillean_Guilder = "Netherlands Antillean Guilder";
    public const New_Israeli_Sheqel = "New Israeli Sheqel";
    public const New_Taiwan_Dollar = "New Taiwan Dollar";
    public const New_Zealand_Dollar = "New Zealand Dollar";
    public const Ngultrum = "Ngultrum";
    public const North_Korean_Won = "North Korean Won";
    public const Norwegian_Krone = "Norwegian Krone";
    public const Nuevo_Sol = "Nuevo Sol";
    public const Ouguiya = "Ouguiya";
    public const Pakistan_Rupee = "Pakistan Rupee";
    public const Pataca = "Pataca";
    public const Pa’anga = "Pa’anga";
    public const Peso_Convertible = "Peso Convertible";
    public const Peso_Uruguayo = "Peso Uruguayo";
    public const Philippine_Peso = "Philippine Peso";
    public const Pound_Sterling = "Pound Sterling";
    public const Pula = "Pula";
    public const Qatari_Rial = "Qatari Rial";
    public const Quetzal = "Quetzal";
    public const Rand = "Rand";
    public const Rial_Omani = "Rial Omani";
    public const Riel = "Riel";
    public const Romanian_Leu = "Romanian Leu";
    public const Rufiyaa = "Rufiyaa";
    public const Rupiah = "Rupiah";
    public const Russian_Ruble = "Russian Ruble";
    public const Rwanda_Franc = "Rwanda Franc";
    public const Saint_Helena_Pound = "Saint Helena Pound";
    public const Saudi_Riyal = "Saudi Riyal";
    public const Serbian_Dinar = "Serbian Dinar";
    public const Seychelles_Rupee = "Seychelles Rupee";
    public const Singapore_Dollar = "Singapore Dollar";
    public const Solomon_Islands_Dollar = "Solomon Islands Dollar";
    public const Som = "Som";
    public const Somali_Shilling = "Somali Shilling";
    public const Somoni = "Somoni";
    public const South_Sudanese_Pound = "South Sudanese Pound";
    public const Sri_Lanka_Rupee = "Sri Lanka Rupee";
    public const Sucre = "Sucre";
    public const Sudanese_Pound = "Sudanese Pound";
    public const Surinam_Dollar = "Surinam Dollar";
    public const Swedish_Krona = "Swedish Krona";
    public const Swiss_Franc = "Swiss Franc";
    public const Syrian_Pound = "Syrian Pound";
    public const Taka = "Taka";
    public const Tala = "Tala";
    public const Tanzanian_Shilling = "Tanzanian Shilling";
    public const Tenge = "Tenge";
    public const Trinidad_and_Tobago_Dollar = "Trinidad and Tobago Dollar";
    public const Tugrik = "Tugrik";
    public const Tunisian_Dinar = "Tunisian Dinar";
    public const Turkish_Lira = "Turkish Lira";
    public const Turkmenistan_New_Manat = "Turkmenistan New Manat";
    public const UAE_Dirham = "UAE Dirham";
    public const US_Dollar = "US Dollar";
    public const Uganda_Shilling = "Uganda Shilling";
    public const Unidad_de_Fomento = "Unidad de Fomento";
    public const Unidad_de_Valor_Real = "Unidad de Valor Real";
    public const Uzbekistan_Sum = "Uzbekistan Sum";
    public const Vatu = "Vatu";
    public const WIR_Euro = "WIR Euro";
    public const WIR_Franc = "WIR Franc";
    public const Won = "Won";
    public const Yemeni_Rial = "Yemeni Rial";
    public const Yen = "Yen";
    public const Yuan_Renminbi = "Yuan Renminbi";
    public const Zambian_Kwacha = "Zambian Kwacha";
    public const Zimbabwe_Dollar = "Zimbabwe Dollar";
    public const Zlloty = "Zloty";

    protected function valueMapping(): array
    {
        return [
            self::ADB_Unit_of_Account => "XUA",
            self::Afghani => "AFN",
            self::Algerian_Dinar => "DZD",
            self::Argentine_Peso => "ARS",
            self::Armenian_Dram => "AMD",
            self::Aruban_Florin => "AWG",
            self::Australian_Dollar => "AUD",
            self::Azerbaijanian_Manat => "AZN",
            self::Bahamian_Dollar => "BSD",
            self::Bahraini_Dinar => "BHD",
            self::Baht => "THB",
            self::Balboa => "PAB",
            self::Barbados_Dollar => "BBD",
            self::Belarussian_Ruble => "BYN",
            self::Belize_Dollar => "BZD",
            self::Bermudian_Dollar => "BMD",
            self::Bolivar => "VEF",
            self::Boliviano => "BOB",
            self::Brazilian_Real => "BRL",
            self::Brunei_Dollar => "BND",
            self::Bulgarian_Lev => "BGN",
            self::Burundi_Franc => "BIF",
            self::CFA_Franc_BCEAO => "XOF",
            self::CFA_Franc_BEAC => "XAF",
            self::CFP_Franc => "XPF",
            self::Cabo_Verde_Escudo => "CVE",
            self::Canadian_Dollar => "CAD",
            self::Cayman_Islands_Dollar => "KYD",
            self::Chilean_Peso => "CLP",
            self::Colombian_Peso => "COP",
            self::Comoro_Franc => "KMF",
            self::Congolese_Franc => "CDF",
            self::Convertible_Mark => "BAM",
            self::Cordoba_Oro => "NIO",
            self::Costa_Rican_Colon => "CRC",
            self::Cuban_Peso => "CUP",
            self::Czech_Koruna => "CZK",
            self::Dalasi => "GMD",
            self::Danish_Krone => "DKK",
            self::Denar => "MKD",
            self::Djibouti_Franc => "DJF",
            self::Dobra => "STN",
            self::Dominican_Peso => "DOP",
            self::Dong => "VND",
            self::East_Caribbean_Dollar => "XCD",
            self::Egyptian_Pound => "EGP",
            self::El_Salvador_Colon => "SVC",
            self::Ethiopian_Birr => "ETB",
            self::Euro => "EUR",
            self::Falkland_Islands_Pound => "FKP",
            self::Fiji_Dollar => "FJD",
            self::Forint => "HUF",
            self::Ghana_Cedi => "GHS",
            self::Gibraltar_Pound => "GIP",
            self::Gourde => "HTG",
            self::Guarani => "PYG",
            self::Guinea_Franc => "GNF",
            self::Guyana_Dollar => "GYD",
            self::Hong_Kong_Dollar => "HKD",
            self::Hryvnia => "UAH",
            self::Iceland_Krona => "ISK",
            self::Indian_Rupee => "INR",
            self::Iranian_Rial => "IRR",
            self::Iraqi_Dinar => "IQD",
            self::Jamaican_Dollar => "JMD",
            self::Jordanian_Dinar => "JOD",
            self::Kenyan_Shilling => "KES",
            self::Kina => "PGK",
            self::Kip => "LAK",
            self::Kuna => "HRK",
            self::Kuwaiti_Dinar => "KWD",
            self::Kwacha => "MWK",
            self::Kwanza => "AOA",
            self::Kyat => "MMK",
            self::Lari => "GEL",
            self::Lebanese_Pound => "LBP",
            self::Lek => "ALL",
            self::Lempira => "HNL",
            self::Leone => "SLE",
            self::Liberian_Dollar => "LRD",
            self::Libyan_Dinar => "LYD",
            self::Lilangeni => "SZL",
            self::Loti => "LSL",
            self::Malagasy_Ariary => "MGA",
            self::Malaysian_Ringgit => "MYR",
            self::Mauritius_Rupee => "MUR",
            self::Mexican_Peso => "MXN",
            self::Moldovan_Leu => "MDL",
            self::Moroccan_Dirham => "MAD",
            self::Mozambique_Metical => "MZN",
            self::Mvdol => "BOV",
            self::Naira => "NGN",
            self::Nakfa => "ERN",
            self::Namibia_Dollar => "NAD",
            self::Nepalese_Rupee => "NPR",
            self::Netherlands_Antillean_Guilder => "ANG",
            self::New_Israeli_Sheqel => "ILS",
            self::New_Taiwan_Dollar => "TWD",
            self::New_Zealand_Dollar => "NZD",
            self::Ngultrum => "BTN",
            self::North_Korean_Won => "KPW",
            self::Norwegian_Krone => "NOK",
            self::Nuevo_Sol => "PEN",
            self::Ouguiya => "MRU",
            self::Pakistan_Rupee => "PKR",
            self::Pataca => "MOP",
            self::Pa’anga => "TOP",
            self::Peso_Convertible => "CUC",
            self::Peso_Uruguayo => "UYU",
            self::Philippine_Peso => "PHP",
            self::Pound_Sterling => "GBP",
            self::Pula => "BWP",
            self::Qatari_Rial => "QAR",
            self::Quetzal => "GTQ",
            self::Rand => "ZAR",
            self::Rial_Omani => "OMR",
            self::Riel => "KHR",
            self::Romanian_Leu => "RON",
            self::Rufiyaa => "MVR",
            self::Rupiah => "IDR",
            self::Russian_Ruble => "RUB",
            self::Rwanda_Franc => "RWF",
            self::Saint_Helena_Pound => "SHP",
            self::Saudi_Riyal => "SAR",
            self::Serbian_Dinar => "RSD",
            self::Seychelles_Rupee => "SCR",
            self::Singapore_Dollar => "SGD",
            self::Solomon_Islands_Dollar => "SBD",
            self::Som => "KGS",
            self::Somali_Shilling => "SOS",
            self::Somoni => "TJS",
            self::South_Sudanese_Pound => "SSP",
            self::Sri_Lanka_Rupee => "LKR",
            self::Sucre => "XSU",
            self::Sudanese_Pound => "SDG",
            self::Surinam_Dollar => "SRD",
            self::Swedish_Krona => "SEK",
            self::Swiss_Franc => "CHF",
            self::Syrian_Pound => "SYP",
            self::Taka => "BDT",
            self::Tala => "WST",
            self::Tanzanian_Shilling => "TZS",
            self::Tenge => "KZT",
            self::Trinidad_and_Tobago_Dollar => "TTD",
            self::Tugrik => "MNT",
            self::Tunisian_Dinar => "TND",
            self::Turkish_Lira => "TRY",
            self::Turkmenistan_New_Manat => "TMT",
            self::UAE_Dirham => "AED",
            self::US_Dollar => "USD",
            self::Uganda_Shilling => "UGX",
            self::Unidad_de_Fomento => "CLF",
            self::Unidad_de_Valor_Real => "COU",
            self::Uzbekistan_Sum => "UZS",
            self::Vatu => "VUV",
            self::WIR_Euro => "CHE",
            self::WIR_Franc => "CHW",
            self::Won => "KRW",
            self::Yemeni_Rial => "YER",
            self::Yen => "JPY",
            self::Yuan_Renminbi => "CNY",
            self::Zambian_Kwacha => "ZMW",
            self::Zimbabwe_Dollar => "ZWL",
            self::Zlloty => "PLN"
        ];
    }

    public function valueToCurrencyNumber(): ?string
    {
        $codes = [
            "ADB Unit of Account" => "965",
            "Afghani" => "971",
            "Algerian Dinar" => "012",
            "Argentine Peso" => "032",
            "Armenian Dram" => "051",
            "Aruban Florin" => "533",
            "Australian Dollar" => "036",
            "Azerbaijanian Manat" => "944",
            "Bahamian Dollar" => "044",
            "Bahraini Dinar" => "048",
            "Baht" => "764",
            "Balboa" => "590",
            "Barbados Dollar" => "052",
            "Belarussian Ruble" => "933",
            "Belize Dollar" => "084",
            "Bermudian Dollar" => "060",
            "Bolivar" => "937",
            "Boliviano" => "068",
            "Brazilian Real" => "986",
            "Brunei Dollar" => "096",
            "Bulgarian Lev" => "975",
            "Burundi Franc" => "108",
            "CFA Franc BCEAO" => "952",
            "CFA Franc BEAC" => "950",
            "CFP Franc" => "953",
            "Cabo Verde Escudo" => "132",
            "Canadian Dollar" => "124",
            "Cayman Islands Dollar" => "136",
            "Chilean Peso" => "152",
            "Colombian Peso" => "170",
            "Comoro Franc" => "174",
            "Congolese Franc" => "976",
            "Convertible Mark" => "977",
            "Cordoba Oro" => "558",
            "Costa Rican Colon" => "188",
            "Cuban Peso" => "192",
            "Czech Koruna" => "203",
            "Dalasi" => "270",
            "Danish Krone" => "208",
            "Denar" => "807",
            "Djibouti Franc" => "262",
            "Dobra" => "930",
            "Dominican Peso" => "214",
            "Dong" => "704",
            "East Caribbean Dollar" => "951",
            "Egyptian Pound" => "818",
            "El Salvador Colon" => "222",
            "Ethiopian Birr" => "230",
            "Euro" => "978",
            "Falkland Islands Pound" => "238",
            "Fiji Dollar" => "242",
            "Forint" => "348",
            "Ghana Cedi" => "936",
            "Gibraltar Pound" => "292",
            "Gourde" => "332",
            "Guarani" => "600",
            "Guinea Franc" => "324",
            "Guyana Dollar" => "328",
            "Hong Kong Dollar" => "344",
            "Hryvnia" => "980",
            "Iceland Krona" => "352",
            "Indian Rupee" => "356",
            "Iranian Rial" => "364",
            "Iraqi Dinar" => "368",
            "Jamaican Dollar" => "388",
            "Jordanian Dinar" => "400",
            "Kenyan Shilling" => "404",
            "Kina" => "598",
            "Kip" => "418",
            "Kuna" => "191",
            "Kuwaiti Dinar" => "414",
            "Kwacha" => "454",
            "Kwanza" => "973",
            "Kyat" => "104",
            "Lari" => "981",
            "Lebanese Pound" => "422",
            "Lek" => "008",
            "Lempira" => "340",
            "Leone" => "925",
            "Liberian Dollar" => "430",
            "Libyan Dinar" => "434",
            "Lilangeni" => "748",
            "Loti" => "426",
            "Malagasy Ariary" => "969",
            "Malaysian Ringgit" => "458",
            "Mauritius Rupee" => "480",
            "Mexican Peso" => "484",
            "Moldovan Leu" => "498",
            "Moroccan Dirham" => "504",
            "Mozambique Metical" => "943",
            "Mvdol" => "984",
            "Naira" => "566",
            "Nakfa" => "232",
            "Namibia Dollar" => "516",
            "Nepalese Rupee" => "524",
            "Netherlands Antillean Guilder" => "532",
            "New Israeli Sheqel" => "376",
            "New Taiwan Dollar" => "901",
            "New Zealand Dollar" => "554",
            "Ngultrum" => "064",
            "North Korean Won" => "408",
            "Norwegian Krone" => "578",
            "Nuevo Sol" => "604",
            "Ouguiya" => "929",
            "Pakistan Rupee" => "586",
            "Pataca" => "446",
            "Pa’anga" => "776",
            "Peso Convertible" => "931",
            "Peso Uruguayo" => "858",
            "Philippine Peso" => "608",
            "Pound Sterling" => "826",
            "Pula" => "072",
            "Qatari Rial" => "634",
            "Quetzal" => "320",
            "Rand" => "710",
            "Rial Omani" => "512",
            "Riel" => "116",
            "Romanian Leu" => "946",
            "Rufiyaa" => "462",
            "Rupiah" => "360",
            "Russian Ruble" => "643",
            "Rwanda Franc" => "646",
            "Saint Helena Pound" => "654",
            "Saudi Riyal" => "682",
            "Serbian Dinar" => "941",
            "Seychelles Rupee" => "690",
            "Singapore Dollar" => "702",
            "Solomon Islands Dollar" => "090",
            "Som" => "417",
            "Somali Shilling" => "706",
            "Somoni" => "972",
            "South Sudanese Pound" => "728",
            "Sri Lanka Rupee" => "144",
            "Sucre" => "994",
            "Sudanese Pound" => "938",
            "Surinam Dollar" => "968",
            "Swedish Krona" => "752",
            "Swiss Franc" => "756",
            "Syrian Pound" => "760",
            "Taka" => "050",
            "Tala" => "882",
            "Tanzanian Shilling" => "834",
            "Tenge" => "398",
            "Trinidad and Tobago Dollar" => "780",
            "Tugrik" => "496",
            "Tunisian Dinar" => "788",
            "Turkish Lira" => "949",
            "Turkmenistan New Manat" => "934",
            "UAE Dirham" => "784",
            "US Dollar" => "840",
            "Uganda Shilling" => "800",
            "Unidad de Fomento" => "990",
            "Unidad de Valor Real" => "970",
            "Uzbekistan Sum" => "860",
            "Vatu" => "548",
            "WIR Euro" => "947",
            "WIR Franc" => "948",
            "Won" => "410",
            "Yemeni Rial" => "886",
            "Yen" => "392",
            "Yuan Renminbi" => "156",
            "Zambian Kwacha" => "967",
            "Zimbabwe Dollar" => "932",
            "Zloty" => "985",
        ];

        return array_key_exists($this->value(), $codes) ? $codes[$this->value()] : null;
    }
}
